#!/usr/bin/env python3
"""Generate the per-modality noise-levels table for the README.

Columns (units inline in each cell, since they differ per modality):
    Modality | Current noise level | Noise limit | Output amplitude

All values are taken at each modality's reference sensor count and reference
bandwidth, straight from ``guti.noise_models.NOISE_MODELS``:
    * current noise level = ``today_best_noise``
    * noise limit         = ``physical_floor_noise``
    * output amplitude    = ``typical_signal_amplitude`` (the empirically
      observed signal, in the same measurement units as the noise)

Usage:
    python scripts/make_noise_levels_table.py            # print table
    python scripts/make_noise_levels_table.py --write    # inject into README
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from guti.noise_models import NOISE_MODELS  # noqa: E402

README_PATH = REPO_ROOT / "README.md"
TABLE_BEGIN = "<!-- BEGIN GENERATED MODALITY NOISE LEVELS -->"
TABLE_END = "<!-- END GENERATED MODALITY NOISE LEVELS -->"

# Display name + short unit label per modality, in presentation order.
# The short unit is appended inline to every value cell for that row.
# Each entry's first field is a tuple of candidate keys (the TD-fNIRS model has
# been registered under both "td_fnirs" and the older "td_fnirs_analytical").
ROWS = [
    (("eeg",), "EEG", "V"),
    (("meg_opm",), "MEG (OPM)", "T"),
    (("meg_squid",), "MEG (SQUID)", "T"),
    (("cw_fnirs",), "CW-fNIRS", "ΔI/I"),
    (("td_fnirs", "td_fnirs_analytical"), "TD-fNIRS", "ΔI/I"),
    (("us_analytical",), "Ultrasound", "pressure ratio"),
    (("fmri_bold",), "fMRI (BOLD)", "fractional BOLD"),
]


def resolve_model(candidates):
    """Return the first registered NoiseModel among candidate keys."""
    for key in candidates:
        if key in NOISE_MODELS:
            return NOISE_MODELS[key]
    raise KeyError(f"No noise model registered for any of {candidates}")


def fmt(value: float, unit: str) -> str:
    """Format a value with its unit, e.g. ``9.25e-08 V``."""
    return f"{value:.3g} {unit}"


def build_table() -> str:
    header = (
        "| Modality | Current noise level | Noise limit | Output amplitude |\n"
        "| --- | ---: | ---: | ---: |"
    )
    lines = [header]
    for candidates, label, unit in ROWS:
        m = resolve_model(candidates)
        lines.append(
            f"| {label} "
            f"| {fmt(m.today_best_noise, unit)} "
            f"| {fmt(m.physical_floor_noise, unit)} "
            f"| {fmt(m.typical_signal_amplitude, unit)} |"
        )
    return "\n".join(lines)


def write_into_readme(table: str) -> None:
    text = README_PATH.read_text()
    if TABLE_BEGIN not in text or TABLE_END not in text:
        raise SystemExit(
            f"Markers not found in {README_PATH}. Add:\n{TABLE_BEGIN}\n{TABLE_END}"
        )
    pre = text.split(TABLE_BEGIN)[0]
    post = text.split(TABLE_END)[1]
    block = (
        f"{TABLE_BEGIN}\n"
        "### Noise Levels\n\n"
        "Per-modality detector noise (per sensor, at the reference sensor count and "
        "bandwidth) versus the typical observed output signal, in matching units. "
        "Generated by `scripts/make_noise_levels_table.py`.\n\n"
        f"{table}\n\n"
        f"{TABLE_END}"
    )
    README_PATH.write_text(pre + block + post)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Inject the table into README.md between the generation markers",
    )
    args = parser.parse_args()

    table = build_table()
    if args.write:
        write_into_readme(table)
        print(f"Wrote noise-levels table into {README_PATH}")
    else:
        print(table)


if __name__ == "__main__":
    main()
